# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/python-tools',
                'doc_host': 'https://cliburn.github.io',
                'git_url': 'https://github.com/cliburn/python-tools',
                'lib_path': 'python_tools'},
  'syms': {'python_tools.core': {'python_tools.core.foo': ('core.html#foo', 'python_tools/core.py')}}}